# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUezoXCv26ydTC3MHpcXD__CYIvofxm6
"""

def bubbleSort(array):
    n = len(array)

    for i in range(n):

        for j in range(0, n-i-1):

            if array[j] > array[j+1] :
                array[j], array[j+1] = array[j+1], array[j]

def binarySearch(array, l, r, x):

    # Check base case
    if r >= l:

        mid = l + (r - l) // 2

        if array[mid] == x:
            return mid

        elif array[mid] > x:
            return binarySearch(array, l, mid-1, x)

        else:
            return binarySearch(array, mid + 1, r, x)

    else:
        return -1

array = [87, 56, 34, 23, 89, 15, 2, 200, 28, 31]
x = input("masukan yang dicari: ")
x = int(x)

bubbleSort(array)

result = binarySearch(array, 0, len(array)-1, x)
result = int(result)
print("Diurutkan jadi:", array)


if result != -1:
    print("indeks ditemukan", (result)+1)
else:
    print("indeks tidak di temukan")

class bubbleSort:


	def __init__(self, angka):
		self.angka = angka
		self.panjang = len(angka)

	def __str__(self):
		return " ".join([str(x)
						for x in self.angka])

	def bubbleSortRecursive(self, n = None):
		if n is None:
			n = self.panjang

		if n == 1:
			return

		for i in range(n - 1):
			if self.angka[i] > self.angka[i + 1]:
				self.angka[i], self.angka[i + 1] = self.angka[i + 1], self.angka[i]

		self.bubbleSortRecursive(n - 1)

def main():
	angka = [90, 34, 23, 1, 21, 43, 120,(-20)]


	sort = bubbleSort(angka)


	sort.bubbleSortRecursive()
	print("dengan sortingan sebagai berikut :\n", sort)


if __name__ == "__main__":
	main()